website/routes/admin.py
import json, os
import requests
import datetime as dt

from core import config
from database import DatabaseManager
from functions import convert_file_size

from flask import Blueprint, render_template
from flask_login import login_required


admin = Blueprint('admin', __name__, static_folder='../static/', template_folder='../templates/admin')
database_manager = DatabaseManager(config.DATABASE)


@admin.route('/', methods=['GET'])
@login_required
def index():
    server_files = [
        (file, convert_file_size(os.path.getsize(os.path.join(config.FILE_UPLOAD_DIR, file))), dt.datetime.fromtimestamp(os.stat(os.path.join(config.FILE_UPLOAD_DIR, file)).st_ctime).strftime('%b %d %Y %I:%M.%S %p'))
        for file in os.listdir(config.FILE_UPLOAD_DIR) 
        if os.path.isfile(os.path.join(config.FILE_UPLOAD_DIR, file))
    ]

    logs = []
    with open(config.SERVICE_LOG, 'r') as file:
        content = file.readlines()
        for line in content:
            try:
                logs.append(json.loads(line))
            except json.JSONDecodeError:
                pass

    data = {
        'server_files_total': len(server_files),
        'log_row_total': len(logs)
    }

    return render_template('admin.html', logs=logs[::-1], server_files=server_files, data=data)

@admin.route('/settings', methods=['GET'])
@login_required
def settings():
    return render_template('settings.html')

website/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required, logout_user, login_user

from core import config
from functions import *

auth = Blueprint('auth', __name__, static_folder='../static/', template_folder='../templates/auth')
logger = Logger(config)

@auth.route('/login', methods=['GET'])
def login():
    return render_template("login.html")

@auth.route('/signup', methods=['GET'])
def signup():
    return render_template('signup.html')

@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/reset-password', methods=['GET'])
@login_required
def reset_password():
    return render_template('reset-password.html', methods=['GET'])

website/routes/main.py
from flask import (Flask, url_for, redirect, Blueprint, render_template)
from core import config

main = Blueprint('main', __name__, static_folder='../static/', template_folder='../templates/main')

@main.route('/', methods=['GET'])
def index():
    return redirect(url_for('main.home'))


@main.route('/home', methods=['GET'])
def home():
    return render_template('home.html')

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Whitelabel Application</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
  </head>
  <body>
    {% include "navbar.html" %}

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          {% if category == 'error' %}

            <div class="alert alert-danger alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>           

          {% else %}
          
            <div class="alert alert-success alert-dismissible fade show" role="alert">
              {{ message }}
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>     

          {% endif %}
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="hero-body">
       {% block content %}
       {% endblock %}
    </div>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
  </body>
</html>

website/templates/navbar.html
{% block content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{{ url_for('admin.index') }}">{{ current_user.username }}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">

            <li class="nav-item">
              <a class="nav-link active" href="{{ url_for('main.index') }}">Home</a>
            </li>

            {% if not current_user.is_authenticated %} 

              <li class="nav-item">
                <a href="{{ url_for('auth.login') }}" class="nav-link">Login</a>
              </li>

              <li class="nav-item">
                <a href="{{ url_for('auth.signup') }}" class="nav-link">Signup</a>
              </li>

            {% endif %}

            {% if current_user.is_authenticated %}

              <li class="nav-item">

                <div class="dropdown">
                  <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                    Settings
                  </button>
                  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton2">
                    <li><a class="nav-link" style="color: black;" href="{{ url_for('user.profile') }}">Profile</a></li>
                    <li><a class="nav-link" style="color: black;" href="{{ url_for('admin.settings') }}">Configuration</a></li>
                    <li><a class="nav-link" style="color: black;" href="{{ url_for('admin.index') }}">Admin Panel</a></li>
                  </ul>
                </div>
              
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
              </li>

            {% endif %}

          </ul>
        </div>
      </div>
    </nav>
{% endblock %}